# Set update schedule for GitHub Actions

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      # check at 3am UTC
      time: "03:00"
    open-pull-requests-limit: 20

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: daily
      # check at 3am UTC
      time: "03:00"
    open-pull-requests-limit: 20
    groups:
      storybook:
        applies-to: version-updates
        patterns:
          - "@storybook/*"
          - "storybook"
          - "storybook-dark-mode"
      docusaurus:
        applies-to: version-updates
        patterns:
          - "@docusaurus/*"
      fortawesome:
        applies-to: version-updates
        patterns:
          - "@fortawesome/*"
      typescript-eslint:
        applies-to: version-updates
        patterns:
          - "@typescript-eslint/*"
          - "typescript-eslint"
