---
# Configuration file for htmltest
# See: https://github.com/wjdp/htmltest

DirectoryPath: website/build
OutputDir: .cache/htmltest
CacheExpires: "12h" # Default is 2 weeks.
ExternalTimeout: 60 # (seconds) default is 15.
IgnoreURLs:
  - https://MR01ANKQ9S-dsn.algolia.net
