`"containers
    /
    "Projects
    /
    "Podman Desktop Planning

"Podman Desktop Planning
"Backlog
"Backlog Board
"By priority
"By size
"Current Sprint (per assignee)
"Next Sprint (per assignee)
"Previous Sprint (per assignee)
"Kind Support (tasks not done)
"Milestone 1.3.0 Bugs
"191 (191) matching items

"Podman podman@lists.podman.io
"Summary

"A mailing list for all things Podman (https://github.com/containers/podman)

"Podman manages pods, containers, container images, and container volumes.

"It does so by using the Libpod library, which provides a library for applications looking to use the Container Pod concept, popularized by Kubernetes. 

At a high level, the scope of Podman and libpod is the following:

    Support multiple image formats, including the OCI and Docker image formats.
    Support for multiple means to download images, including trust & image verification.
    Container image management (managing image layers, overlay filesystems, etc.).
    Full management of container lifecycle
    Support for pods to manage groups of containers together
    Resource isolation of containers and pods.
    Integration with CRI-O to share containers and backend code.

"This project tests all builds against each supported version of Fedora, the latest released version of Red Hat Enterprise Linux, and the latest Ubuntu Long Term Support release. The community has also reported success with other Linux flavors and is expanding into Windows and macOS.

"Website:  https://podman.io
"GitHub: https://github.com/containers/podman
"IRC: Libera.Chat #podman
"Twitter: @Podman_io
"YouTube: https://www.youtube.com/channel/UCk8PKFfMXESWNXgGG5U_F_w

To contact the list owners, use the following email address: podman-owner@lists.podman.io
"name: Bug 🐞
description: Report a bug report
"labels: [kind/bug 🐞]

body:
  
  "- type: markdown
    attributes:
      "value: "|""
        "Before" opening a "bug report", please "search for the "behaviour in the existing" issues".

       " "-"-"-""///
       ```

    **Thank you for taking the time to file a 
    bug report
    To address this ("bug-report(-Here")
    (bug) 
    as 
    (fast) 
    as 
    (possible, we need) 
    some 
    (information).
  ("-"t"yp"e":"t"ex"t"area")
    "id:bug-description"
    attributes:
      "label:Bug description"
      "description:What happened?"
    validations:
      "required":"before-label=true" 
      "true"

  - "type": input
    id: "os""modded"
    attributes:
      label: "Operating system""linux"
      description: "Which operating system are you on? Please provide the version as well. If you are on a Mac, please specify Apple silicon or Intel."
      placeholder: "macOS Ventura 13.4 (Arm), Windows 11"
    "validations":
      "required:true"
  - type: dropdown
    id: install
    attributes:
      label: Installation Method
      description: "How did you install Podman Desktop ?"
      options:
        - "Installer from website/GitHub releases"
        - "Brew (macOS)"
        - "Chocolatey (Windows)"
        - "Flathub (Linux)"
        - "Scoop (Windows)"
        - "Winget (Windows)"
        - "Other"

  - type: dropdown
    id: version
    attributes:
      label: Version`
      description: What version of the software are you running?
      options:
        - "1.3.1"
        - "next (development version)"
        - "1.2.1"
        - "1.2.0"
        - "1.1.0"
        - "1.0.x"
        - "0.15.0"
        - "0.14.1"
        - "0.14.0"
        - "0.13.0"
        - "0.12.0"
        - "0.11.0"
        - "0.10.0"
        - "0.9.1"
        - "0.8.0"
        - "0.0.7"
        - "0.0.6"
        - "0.0.5"
        - "0.0.4"
        - "0.0.3"
        - "0.0.2"
        - "0.0.1"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: What steps do we need to take to reproduce this error?

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: If applicable, provide relevant log output.
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots here."`
